@extends('layouts.app')

@section('title', 'Home')
@section('page-title', 'Overview')

@section('content')
<section class="relative overflow-hidden rounded-3xl bg-slate-950 px-6 py-8 text-white shadow-xl shadow-slate-900/10 sm:px-8 sm:py-10"><div class="relative max-w-2xl"><p class="text-sm font-semibold uppercase tracking-[0.2em] text-indigo-300">TaskFlow workspace</p><h2 class="mt-4 text-3xl font-semibold tracking-tight sm:text-4xl">Good to see you, {{ filled(auth()->user()->name) ? auth()->user()->name : auth()->user()->email }}.</h2><p class="mt-4 max-w-xl text-base leading-7 text-slate-300">Your projects, tasks, activity, and dashboard are ready in one workspace.</p></div></section>
<section class="mt-8"><div class="mb-4"><p class="text-sm font-semibold text-slate-900">Workspace modules</p><p class="mt-1 text-sm text-slate-500">Open the area you are authorized to use.</p></div><div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
@can('projects.view')<a href="{{ route('projects.index') }}" class="group rounded-2xl border border-indigo-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-indigo-300 hover:shadow-md">@else<article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm" aria-disabled="true">@endcan<div class="flex items-start justify-between gap-3"><span class="grid size-10 place-items-center rounded-xl bg-indigo-100 text-sm font-bold text-indigo-700">P</span><span class="rounded-full bg-indigo-50 px-2.5 py-1 text-[11px] font-semibold text-indigo-700">Projects</span></div><h3 class="mt-6 font-semibold text-slate-950">Projects</h3><p class="mt-2 text-sm leading-6 text-slate-500">Plan initiatives, ownership, and delivery dates.</p>@can('projects.view')</a>@else</article>@endcan
@can('tasks.view')<a href="{{ route('tasks.index') }}" class="group rounded-2xl border border-sky-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-sky-300 hover:shadow-md">@else<article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm" aria-disabled="true">@endcan<div class="flex items-start justify-between gap-3"><span class="grid size-10 place-items-center rounded-xl bg-sky-100 text-sm font-bold text-sky-700">T</span><span class="rounded-full bg-sky-50 px-2.5 py-1 text-[11px] font-semibold text-sky-700">Tasks</span></div><h3 class="mt-6 font-semibold text-slate-950">Tasks</h3><p class="mt-2 text-sm leading-6 text-slate-500">Turn project plans into focused, actionable work.</p>@can('tasks.view')</a>@else</article>@endcan
@can('activity.view')<a href="{{ route('activity.index') }}" class="group rounded-2xl border border-violet-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-violet-300 hover:shadow-md">@else<article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm" aria-disabled="true">@endcan<div class="flex items-start justify-between gap-3"><span class="grid size-10 place-items-center rounded-xl bg-violet-100 text-sm font-bold text-violet-700">A</span><span class="rounded-full bg-violet-50 px-2.5 py-1 text-[11px] font-semibold text-violet-700">Activity</span></div><h3 class="mt-6 font-semibold text-slate-950">Activity</h3><p class="mt-2 text-sm leading-6 text-slate-500">Keep meaningful team changes easy to follow.</p>@can('activity.view')</a>@else</article>@endcan
@can('viewDashboard')<a href="{{ route('dashboard.index') }}" class="group rounded-2xl border border-emerald-200 bg-white p-5 shadow-sm transition hover:-translate-y-0.5 hover:border-emerald-300 hover:shadow-md">@else<article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm" aria-disabled="true">@endcan<div class="flex items-start justify-between gap-3"><span class="grid size-10 place-items-center rounded-xl bg-emerald-100 text-sm font-bold text-emerald-700">D</span><span class="rounded-full bg-emerald-50 px-2.5 py-1 text-[11px] font-semibold text-emerald-700">Dashboard</span></div><h3 class="mt-6 font-semibold text-slate-950">Dashboard</h3><p class="mt-2 text-sm leading-6 text-slate-500">Bring priorities and progress into one clear view.</p>@can('viewDashboard')</a>@else</article>@endcan
</div></section>
@endsection
