<div>
    <section class="mt-7 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm" aria-label="Task filters">
        <form method="GET" wire:submit="apply" class="grid gap-4 xl:grid-cols-4">
            <div class="xl:col-span-2"><label for="task-search" class="mb-2 block text-sm font-semibold text-slate-700">Search</label><input id="task-search" name="q" wire:model.live.debounce.300ms="q" placeholder="Search number, title, or description" class="block w-full rounded-xl border border-slate-300 px-4 py-3 text-sm outline-none transition focus:border-indigo-500 focus:ring-4 focus:ring-indigo-500/15"><x-form-error field="q" /></div>
            <div><label for="task-project" class="mb-2 block text-sm font-semibold text-slate-700">Project</label><select id="task-project" name="project_id" wire:model.live="projectId" class="block w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm"><option value="">All projects</option>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->name }}</option>@endforeach</select><x-form-error field="projectId" /></div>
            <div><label for="task-assignee" class="mb-2 block text-sm font-semibold text-slate-700">Assignee</label><select id="task-assignee" name="assignee_id" wire:model.live="assigneeId" class="block w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm"><option value="">All assignees</option>@foreach($assignees as $user)<option value="{{ $user->id }}">{{ $user->name ?: $user->email }}</option>@endforeach</select><x-form-error field="assigneeId" /></div>

            <fieldset class="xl:col-span-3"><legend class="mb-2 text-sm font-semibold text-slate-700">Status</legend><div class="flex flex-wrap gap-2">@foreach($statusOptions as $status)<label class="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm"><input type="checkbox" name="statuses[]" value="{{ $status->value }}" wire:model.live="statuses">{{ ucwords(str_replace('_', ' ', $status->value)) }}</label>@endforeach</div><x-form-error field="statuses" /></fieldset>
            <fieldset><legend class="mb-2 text-sm font-semibold text-slate-700">Priority</legend><div class="flex flex-wrap gap-2">@foreach($priorityOptions as $priority)<label class="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm"><input type="checkbox" name="priorities[]" value="{{ $priority->value }}" wire:model.live="priorities">{{ ucfirst($priority->value) }}</label>@endforeach</div><x-form-error field="priorities" /></fieldset>
            <fieldset class="xl:col-span-2"><legend class="mb-2 text-sm font-semibold text-slate-700">Work type</legend><div class="flex flex-wrap gap-2">@foreach($typeOptions as $type)<label class="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-3 py-2 text-sm"><input type="checkbox" name="types[]" value="{{ $type->value }}" wire:model.live="types">{{ ucfirst($type->value) }}</label>@endforeach</div><x-form-error field="types" /></fieldset>
            <div><label for="task-reporter" class="mb-2 block text-sm font-semibold text-slate-700">Reporter</label><select id="task-reporter" name="reporter_id" wire:model.live="reporterId" class="block w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm"><option value="">All reporters</option>@foreach($reporters as $user)<option value="{{ $user->id }}">{{ $user->name ?: $user->email }}</option>@endforeach</select></div>
            <div><label for="task-parent" class="mb-2 block text-sm font-semibold text-slate-700">Parent</label><select id="task-parent" name="parent_id" wire:model.live="parentId" class="block w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm"><option value="">All parent states</option><option value="0">No parent</option>@foreach($parents as $parent)<option value="{{ $parent->id }}">{{ $parent->number }} · {{ $parent->title }}</option>@endforeach</select></div>
            <div><label for="task-label" class="mb-2 block text-sm font-semibold text-slate-700">Label</label><select id="task-label" name="label_ids[]" wire:model.live="labelIds" multiple class="block w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm">@foreach($labels as $label)<option value="{{ $label->id }}">{{ $label->name }}</option>@endforeach</select><p class="mt-1 text-xs text-slate-500">Choose one or more labels.</p></div>
            <div><label for="task-due-after" class="mb-2 block text-sm font-semibold text-slate-700">Due after</label><input id="task-due-after" type="date" name="due_after" wire:model.live="dueAfter" class="block w-full rounded-xl border border-slate-300 px-4 py-3 text-sm"></div>
            <div><label for="task-due-before" class="mb-2 block text-sm font-semibold text-slate-700">Due before</label><input id="task-due-before" type="date" name="due_before" wire:model.live="dueBefore" class="block w-full rounded-xl border border-slate-300 px-4 py-3 text-sm"></div>
            <div class="flex items-end"><label class="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-3 text-sm font-semibold text-slate-700"><input type="checkbox" name="overdue" value="1" wire:model.live="overdue">Overdue only</label></div>
            <div><label for="task-sort" class="mb-2 block text-sm font-semibold text-slate-700">Sort</label><select id="task-sort" name="sort" wire:model.live="sort" class="block w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm"><option value="-created_at">Newest</option><option value="created_at">Oldest</option><option value="due_at">Due date</option><option value="-priority">Priority</option><option value="status">Status</option><option value="number">Number</option><option value="rank">Rank</option></select><x-form-error field="sort" /></div>
            <div class="flex items-end gap-3"><x-button class="flex-1">Apply filters</x-button><button type="button" wire:click="clear" class="rounded-xl px-4 py-2.5 text-sm font-semibold text-slate-600 hover:bg-slate-100 focus:outline-none focus:ring-4 focus:ring-indigo-500/15">Clear</button></div>
        </form>
    </section>

    <div wire:loading class="mt-4 text-sm font-medium text-indigo-700" role="status">Updating task list…</div>

    @if ($tasks->isEmpty())
        <section class="mt-7 rounded-2xl border border-dashed border-slate-300 bg-white px-6 py-14 text-center shadow-sm"><span class="mx-auto grid size-12 place-items-center rounded-2xl bg-indigo-100 text-lg font-bold text-indigo-700">T</span><h3 class="mt-5 text-lg font-semibold text-slate-950">{{ $q !== '' || $statuses !== [] || $types !== [] || $priorities !== [] || $projectId || $assigneeId || $reporterId || $labelIds !== [] || $parentId || $dueBefore || $dueAfter || $overdue ? 'No tasks match this view' : 'No tasks are visible yet' }}</h3><p class="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-500">Adjust the filters to broaden your results.</p></section>
    @else
        <section class="mt-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm" wire:loading.class="opacity-60">
            <div class="hidden overflow-x-auto lg:block"><table class="min-w-full divide-y divide-slate-100 text-left text-sm"><thead class="bg-slate-50 text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-4">Task</th><th class="px-5 py-4">Project</th><th class="px-5 py-4">Assignee</th><th class="px-5 py-4">Status</th><th class="px-5 py-4">Priority</th><th class="px-5 py-4">Due</th></tr></thead><tbody class="divide-y divide-slate-100">@foreach($tasks as $task)<tr class="transition hover:bg-slate-50"><td class="px-5 py-4"><a class="font-semibold text-indigo-700 hover:text-indigo-600" href="{{ route('tasks.show', $task) }}">{{ $task->number }}</a><p class="mt-1 font-medium text-slate-900">{{ $task->title }}</p><p class="mt-1 text-xs text-slate-500">{{ ucfirst($task->type->value) }}</p></td><td class="px-5 py-4 text-slate-600">{{ $task->project->name }}</td><td class="px-5 py-4 text-slate-600">{{ $task->assignee?->name ?: $task->assignee?->email ?: 'Unassigned' }}</td><td class="px-5 py-4"><x-status-badge :status="$task->status" /></td><td class="px-5 py-4"><x-priority-badge :priority="$task->priority" /></td><td class="px-5 py-4 text-sm text-slate-500">{{ $task->due_at?->format('M j, Y') ?? '—' }}</td></tr>@endforeach</tbody></table></div>
            <div class="divide-y divide-slate-100 lg:hidden">@foreach($tasks as $task)<a href="{{ route('tasks.show', $task) }}" class="block p-5 transition hover:bg-slate-50"><div class="flex items-start justify-between gap-3"><div class="min-w-0"><p class="text-xs font-semibold text-indigo-700">{{ $task->number }}</p><p class="mt-1 truncate font-semibold text-slate-950">{{ $task->title }}</p><p class="mt-1 text-sm text-slate-500">{{ $task->project->name }} · {{ $task->assignee?->name ?: 'Unassigned' }}</p></div><div class="flex shrink-0 flex-col items-end gap-2"><x-status-badge :status="$task->status" /><x-priority-badge :priority="$task->priority" /></div></div></a>@endforeach</div>
            <div class="border-t border-slate-100 px-5 py-4">{{ $tasks->links() }}</div>
        </section>
    @endif
</div>
