@extends('layouts.app')

@section('title', 'Project members')
@section('page-title', 'Project members')

@section('content')
    <div class="mx-auto max-w-6xl"><section class="rounded-3xl bg-slate-950 p-7 text-white shadow-xl shadow-slate-900/10"><a href="{{ route('projects.show', $project) }}" class="text-sm font-semibold text-indigo-300 hover:text-white">← {{ $project->name }}</a><h2 class="mt-5 text-3xl font-semibold tracking-tight">Project membership</h2><p class="mt-2 text-sm text-slate-300">Manage the people who can collaborate on this project. Owner: {{ $project->owner->name ?: $project->owner->email }}</p></section>
        <section class="mt-7 grid gap-7 lg:grid-cols-[0.8fr_1.2fr]"><form method="POST" action="{{ route('projects.members.store', $project) }}" class="h-fit rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">@csrf<h3 class="text-lg font-semibold text-slate-950">Add a member</h3><p class="mt-1 text-sm text-slate-500">Choose an existing TaskFlow user and their project role.</p><div class="mt-5 space-y-4"><div><label for="user_id" class="mb-2 block text-sm font-semibold text-slate-700">User</label><select id="user_id" name="user_id" required class="block w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm" @disabled($availableUsers->isEmpty())>@forelse($availableUsers as $user)<option value="{{ $user->id }}">{{ $user->name ?: $user->email }} — {{ $user->email }}</option>@empty<option>No available users</option>@endforelse</select>@error('user_id')<p class="mt-2 text-sm font-medium text-rose-600">{{ $message }}</p>@enderror</div><div><label for="member_role" class="mb-2 block text-sm font-semibold text-slate-700">Project role</label><select id="member_role" name="member_role" required class="block w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm">@foreach($roles as $role)<option value="{{ $role->value }}">{{ ucfirst($role->value) }}</option>@endforeach</select>@error('member_role')<p class="mt-2 text-sm font-medium text-rose-600">{{ $message }}</p>@enderror</div></div><button type="submit" @disabled($availableUsers->isEmpty()) class="mt-6 rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white disabled:cursor-not-allowed disabled:opacity-50">Add member</button></form>
            <section class="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 px-6 py-5"><h3 class="text-lg font-semibold text-slate-950">Members ({{ $memberships->count() }})</h3></div><div class="divide-y divide-slate-100">@foreach($memberships as $membership)<div class="flex flex-col gap-3 px-5 py-4 sm:flex-row sm:items-center sm:justify-between sm:px-6"><div><p class="font-semibold text-slate-900">{{ $membership->user->name ?: $membership->user->email }}</p><p class="mt-1 text-xs text-slate-500">{{ $membership->user->email }} · Joined {{ $membership->joined_at?->format('M j, Y') ?? 'today' }}</p></div><div class="flex flex-wrap items-center gap-3"><span class="inline-flex rounded-full bg-indigo-50 px-2.5 py-1 text-xs font-semibold text-indigo-700 ring-1 ring-inset ring-indigo-200">{{ ucfirst($membership->member_role->value) }}</span>@if($membership->user_id !== $project->owner_id)<form method="POST" action="{{ route('projects.members.update', [$project, $membership->user]) }}" class="flex items-center gap-2">@csrf @method('PATCH')<label class="sr-only" for="member-role-{{ $membership->id }}">Project role</label><select id="member-role-{{ $membership->id }}" name="member_role" class="rounded-lg border border-slate-300 px-2 py-1 text-xs">@foreach($roles as $role)<option value="{{ $role->value }}" @selected($membership->member_role === $role)>{{ ucfirst($role->value) }}</option>@endforeach</select><button type="submit" class="text-sm font-semibold text-indigo-700 hover:text-indigo-600">Update role</button></form><form method="POST" action="{{ route('projects.members.destroy', [$project, $membership->user]) }}" data-confirm="Remove this person from the project?">@csrf @method('DELETE')<button type="submit" class="text-sm font-semibold text-rose-700 hover:text-rose-600">Remove</button></form>@endif</div></div>@endforeach</div></section>
        </section>
    </div>
@endsection
