@extends('layouts.app')

@section('title', $project->name)
@section('page-title', 'Project details')

@section('content')
    <div class="mx-auto max-w-6xl">
        <section class="rounded-3xl bg-slate-950 p-7 text-white shadow-xl shadow-slate-900/10"><a href="{{ route('projects.index') }}" class="text-sm font-semibold text-indigo-300 hover:text-white">← All projects</a><div class="mt-5 flex flex-wrap items-center gap-3"><h2 class="text-3xl font-semibold tracking-tight">{{ $project->name }}</h2><span class="rounded bg-white/10 px-2 py-1 font-mono text-sm">{{ $project->key }}</span><x-status-badge kind="project" :status="$project->status" /></div><p class="mt-3 max-w-3xl whitespace-pre-line text-sm leading-7 text-slate-300">{{ $project->description ?: 'No description has been added yet.' }}</p><div class="mt-6 flex flex-wrap gap-2">@can('update', $project)@if(in_array($project->status, [\Modules\Projects\Enums\ProjectStatus::Draft, \Modules\Projects\Enums\ProjectStatus::Active], true))<a href="{{ route('projects.edit', $project) }}" class="rounded-xl bg-white px-4 py-2.5 text-sm font-semibold text-slate-950">Edit project</a>@endif @if($project->status === \Modules\Projects\Enums\ProjectStatus::Draft)<form method="POST" action="{{ route('projects.activate', $project) }}">@csrf @method('PATCH')<button type="submit" class="rounded-xl bg-emerald-400 px-4 py-2.5 text-sm font-semibold text-emerald-950">Activate project</button></form>@elseif($project->status === \Modules\Projects\Enums\ProjectStatus::Active)<form method="POST" action="{{ route('projects.complete', $project) }}">@csrf @method('PATCH')<button type="submit" class="rounded-xl bg-sky-400 px-4 py-2.5 text-sm font-semibold text-sky-950">Complete project</button></form>@elseif($project->status === \Modules\Projects\Enums\ProjectStatus::Completed)<form method="POST" action="{{ route('projects.activate', $project) }}">@csrf @method('PATCH')<button type="submit" class="rounded-xl bg-emerald-400 px-4 py-2.5 text-sm font-semibold text-emerald-950">Reopen project</button></form>@endif @endcan @can('archive', $project)@if($project->status !== \Modules\Projects\Enums\ProjectStatus::Archived)<form method="POST" action="{{ route('projects.archive', $project) }}" data-confirm="Archive this project? New tasks can no longer be created.">@csrf @method('PATCH')<button type="submit" class="rounded-xl border border-amber-300/40 px-4 py-2.5 text-sm font-semibold text-amber-100">Archive</button></form>@endif @endcan @can('manageMembers', $project)@if(in_array($project->status, [\Modules\Projects\Enums\ProjectStatus::Draft, \Modules\Projects\Enums\ProjectStatus::Active], true))<a href="{{ route('projects.members.index', $project) }}" class="rounded-xl border border-white/20 px-4 py-2.5 text-sm font-semibold text-white">Manage members</a>@endif @endcan</div></section>
        <section class="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-4">@foreach ([['label' => 'Owner', 'value' => $project->owner->name ?: $project->owner->email], ['label' => 'Members', 'value' => $project->memberships_count.' people'], ['label' => 'Tasks', 'value' => $project->tasks_count.' tasks'], ['label' => 'Due date', 'value' => $project->due_at?->format('M j, Y') ?? 'Not set']] as $detail)<article class="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><p class="text-xs font-semibold uppercase tracking-[0.15em] text-slate-400">{{ $detail['label'] }}</p><p class="mt-3 font-semibold text-slate-900">{{ $detail['value'] }}</p></article>@endforeach</section>
        <section class="mt-7 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div class="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><h3 class="text-lg font-semibold text-slate-950">Project tasks</h3><p class="mt-1 text-sm text-slate-500">{{ $project->status === \Modules\Projects\Enums\ProjectStatus::Archived ? 'This project is archived and is read-only.' : ($project->status === \Modules\Projects\Enums\ProjectStatus::Active ? 'This project is active and ready for focused work.' : 'Activate this project before creating tasks.') }}</p></div><div class="flex flex-wrap gap-2"><a href="{{ route('tasks.index', ['project_id' => $project->id]) }}" class="rounded-xl border border-slate-200 px-4 py-2.5 text-sm font-semibold text-slate-700">View tasks</a>@can('create', [\Modules\Tasks\Models\Task::class, $project])@if($project->status === \Modules\Projects\Enums\ProjectStatus::Active)<a href="{{ route('tasks.create', $project) }}" class="rounded-xl bg-indigo-600 px-4 py-2.5 text-sm font-semibold text-white">Create task</a>@endif @endcan</div></div></section>
        @if($canViewActivity)
        <section class="mt-7 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-6"><div class="flex items-center justify-between gap-4"><div><h3 class="text-lg font-semibold text-slate-950">Recent activity</h3><p class="mt-1 text-sm text-slate-500">Relevant changes for this project.</p></div>@if($canViewActivity)<a href="{{ route('activity.index', ['project' => $project->id]) }}" class="text-sm font-semibold text-indigo-700">View all activity</a>@endif</div><div class="mt-5 space-y-4">@forelse($activities as $activity)<div class="border-l-2 border-indigo-200 pl-4"><p class="font-semibold text-slate-900">{{ \Modules\Activity\Support\ActivityDisplay::label($activity) }}</p>@if($summary = \Modules\Activity\Support\ActivityDisplay::summary($activity))<p class="mt-1 text-sm text-slate-600">{{ $summary }}</p>@endif<p class="mt-1 text-xs text-slate-500">{{ $activity->causer?->name ?: 'System' }} · {{ $activity->created_at->diffForHumans() }}</p></div>@empty<p class="rounded-xl border border-dashed border-slate-300 px-5 py-8 text-center text-sm text-slate-500">No activity for this project yet.</p>@endforelse</div></section>
        @endif
    </div>
@endsection
