@extends('layouts.app')

@section('title', 'Activity')
@section('page-title', 'Activity')

@section('content')
    <section class="rounded-3xl bg-slate-950 p-7 text-white shadow-xl shadow-slate-900/10"><p class="text-sm font-semibold uppercase tracking-[0.18em] text-indigo-300">Workspace history</p><h2 class="mt-3 text-3xl font-semibold tracking-tight">Meaningful changes, in context.</h2><p class="mt-2 max-w-2xl text-sm leading-6 text-slate-300">Review the project and task activity that is relevant to your current workspace access.</p></section>
    <section class="mt-7 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><form method="GET" class="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><div><label for="event" class="mb-2 block text-sm font-semibold text-slate-700">Event</label><select id="event" name="event" class="block w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm"><option value="">All events</option>@foreach($options['events'] as $event)<option value="{{ $event }}" @selected(($filters['event'] ?? '') === $event)>{{ \Modules\Activity\Support\ActivityDisplay::label(new \Spatie\Activitylog\Models\Activity(['event' => $event])) }}</option>@endforeach</select></div><div><label for="project" class="mb-2 block text-sm font-semibold text-slate-700">Project</label><select id="project" name="project" class="block w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm"><option value="">All projects</option>@foreach($options['projects'] as $project)<option value="{{ $project->id }}" @selected((string) ($filters['project'] ?? '') === (string) $project->id)>{{ $project->name }}</option>@endforeach</select></div><div><label for="task" class="mb-2 block text-sm font-semibold text-slate-700">Task</label><select id="task" name="task" class="block w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm"><option value="">All tasks</option>@foreach($options['tasks'] as $task)<option value="{{ $task->id }}" @selected((string) ($filters['task'] ?? '') === (string) $task->id)>{{ $task->number }} — {{ $task->title }}</option>@endforeach</select></div><div><label for="actor" class="mb-2 block text-sm font-semibold text-slate-700">Actor</label><select id="actor" name="actor" class="block w-full rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm"><option value="">All actors</option>@foreach($options['actors'] as $actor)<option value="{{ $actor->id }}" @selected((string) ($filters['actor'] ?? '') === (string) $actor->id)>{{ $actor->name ?: $actor->email }}</option>@endforeach</select></div><div><label for="date_from" class="mb-2 block text-sm font-semibold text-slate-700">Date from</label><input id="date_from" type="date" name="date_from" value="{{ $filters['date_from'] ?? '' }}" class="block w-full rounded-xl border border-slate-300 px-4 py-3 text-sm"></div><div><label for="date_to" class="mb-2 block text-sm font-semibold text-slate-700">Date to</label><input id="date_to" type="date" name="date_to" value="{{ $filters['date_to'] ?? '' }}" class="block w-full rounded-xl border border-slate-300 px-4 py-3 text-sm"></div><div class="flex items-end gap-3"><button type="submit" class="rounded-xl bg-slate-900 px-5 py-3 text-sm font-semibold text-white">Apply filters</button>@if($filters)<a href="{{ route('activity.index') }}" class="rounded-xl px-4 py-3 text-sm font-semibold text-slate-600 hover:bg-slate-100">Clear</a>@endif</div></form></section>
    <section class="mt-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">@forelse($activities as $activity)<article class="border-b border-slate-100 px-5 py-5 sm:px-6"><div class="flex flex-col gap-2 sm:flex-row sm:items-start sm:justify-between"><div><p class="font-semibold text-slate-900">{{ \Modules\Activity\Support\ActivityDisplay::label($activity) }}</p>@if($summary = \Modules\Activity\Support\ActivityDisplay::summary($activity))<p class="mt-1 text-sm leading-6 text-slate-600">{{ $summary }}</p>@endif<p class="mt-2 text-xs text-slate-500">{{ $activity->causer?->name ?: 'System' }} · {{ $activity->created_at->diffForHumans() }}</p></div><span class="text-xs text-slate-400">{{ $activity->created_at->format('M j, Y · H:i') }}</span></div></article>@empty<div class="px-6 py-14 text-center"><p class="font-semibold text-slate-900">No activity is available in your workspace yet.</p><p class="mt-2 text-sm text-slate-500">Try adjusting filters or check back when work changes.</p></div>@endforelse@if($activities->hasPages())<div class="px-6 py-4">{{ $activities->links() }}</div>@endif</section>
@endsection
