@extends('layouts.app')

@section('title', 'Tasks')
@section('page-title', 'Tasks')

@section('content')
    <section class="rounded-3xl bg-slate-950 p-7 text-white shadow-xl shadow-slate-900/10">
        <p class="text-sm font-semibold uppercase tracking-[0.18em] text-indigo-300">Task workspace</p>
        <h2 class="mt-3 text-3xl font-semibold tracking-tight">Make project work visible and actionable.</h2>
        <p class="mt-2 max-w-2xl text-sm leading-6 text-slate-300">Filter by ownership, project, priority, status, and delivery date without losing the wider context.</p>
    </section>

    <section class="mt-7 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
        <form method="GET" class="grid gap-3 md:grid-cols-2 xl:grid-cols-4">
            <input name="q" value="{{ request('q') }}" placeholder="Search number or title" aria-label="Search tasks" class="rounded-xl border border-slate-300 px-4 py-3 text-sm outline-none transition focus:border-indigo-500 focus:ring-4 focus:ring-indigo-500/15">
            <select name="project_id" aria-label="Project" class="rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm outline-none transition focus:border-indigo-500 focus:ring-4 focus:ring-indigo-500/15"><option value="">All projects</option>@foreach($projects as $project)<option value="{{ $project->id }}" @selected(request('project_id') == $project->id)>{{ $project->name }}</option>@endforeach</select>
            <select name="status" aria-label="Status" class="rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm outline-none transition focus:border-indigo-500 focus:ring-4 focus:ring-indigo-500/15"><option value="">All statuses</option>@foreach($statuses as $status)<option value="{{ $status->value }}" @selected(request('status') === $status->value)>{{ ucwords(str_replace('_', ' ', $status->value)) }}</option>@endforeach</select>
            <select name="type" aria-label="Work type" class="rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm outline-none transition focus:border-indigo-500 focus:ring-4 focus:ring-indigo-500/15"><option value="">All types</option>@foreach($types as $type)<option value="{{ $type->value }}" @selected(request('type') === $type->value)>{{ ucfirst($type->value) }}</option>@endforeach</select>
            <select name="priority" aria-label="Priority" class="rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm outline-none transition focus:border-indigo-500 focus:ring-4 focus:ring-indigo-500/15"><option value="">All priorities</option>@foreach($priorities as $priority)<option value="{{ $priority->value }}" @selected(request('priority') === $priority->value)>{{ ucfirst($priority->value) }}</option>@endforeach</select>
            <select name="assignee_id" aria-label="Assignee" class="rounded-xl border border-slate-300 bg-white px-4 py-3 text-sm outline-none transition focus:border-indigo-500 focus:ring-4 focus:ring-indigo-500/15"><option value="">All assignees</option>@foreach($users as $user)<option value="{{ $user->id }}" @selected(request('assignee_id') == $user->id)>{{ $user->name ?: $user->email }}</option>@endforeach</select>
            <input type="date" name="due_before" value="{{ request('due_before') }}" aria-label="Due before" class="rounded-xl border border-slate-300 px-4 py-3 text-sm outline-none transition focus:border-indigo-500 focus:ring-4 focus:ring-indigo-500/15">
            <div class="grid grid-cols-2 gap-3"><select name="sort" aria-label="Sort by" class="rounded-xl border border-slate-300 bg-white px-3 py-3 text-sm"><option value="created_at">Newest</option>@foreach(['due_at' => 'Due date', 'priority' => 'Priority', 'status' => 'Status', 'number' => 'Number'] as $key => $label)<option value="{{ $key }}" @selected(request('sort') === $key)>{{ $label }}</option>@endforeach</select><select name="direction" aria-label="Sort direction" class="rounded-xl border border-slate-300 bg-white px-3 py-3 text-sm"><option value="desc">Descending</option><option value="asc" @selected(request('direction') === 'asc')>Ascending</option></select></div>
            <div class="flex gap-3"><button type="submit" class="flex-1 rounded-xl bg-slate-900 px-4 py-3 text-sm font-semibold text-white transition hover:bg-slate-700">Apply filters</button>@if(request()->hasAny(['q', 'project_id', 'status', 'type', 'priority', 'assignee_id', 'due_before', 'sort', 'direction']))<a href="{{ route('tasks.index') }}" class="rounded-xl px-4 py-3 text-sm font-semibold text-slate-600 hover:bg-slate-100">Clear</a>@endif</div>
        </form>
    </section>

    @if ($tasks->isEmpty())
        <section class="mt-7 rounded-2xl border border-dashed border-slate-300 bg-white px-6 py-14 text-center shadow-sm"><span class="mx-auto grid size-12 place-items-center rounded-2xl bg-indigo-100 text-lg font-bold text-indigo-700">T</span><h3 class="mt-5 text-lg font-semibold text-slate-950">{{ request()->query() ? 'No tasks match this view' : 'No tasks are visible yet' }}</h3><p class="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-500">{{ request()->query() ? 'Adjust the filters to broaden your results.' : 'Tasks assigned to you or available through your project role will appear here.' }}</p></section>
    @else
        <section class="mt-7 overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
            <div class="hidden overflow-x-auto lg:block"><table class="min-w-full divide-y divide-slate-100 text-left text-sm"><thead class="bg-slate-50 text-xs font-semibold uppercase tracking-wide text-slate-500"><tr><th class="px-5 py-4">Task</th><th class="px-5 py-4">Project</th><th class="px-5 py-4">Assignee</th><th class="px-5 py-4">Status</th><th class="px-5 py-4">Priority</th><th class="px-5 py-4">Due</th></tr></thead><tbody class="divide-y divide-slate-100">@foreach($tasks as $task)<tr class="transition hover:bg-slate-50"><td class="px-5 py-4"><a class="font-semibold text-indigo-700 hover:text-indigo-600" href="{{ route('tasks.show', $task) }}">{{ $task->number }}</a><p class="mt-1 font-medium text-slate-900">{{ $task->title }}</p><p class="mt-1 text-xs text-slate-500">{{ ucfirst($task->type->value) }}</p></td><td class="px-5 py-4 text-slate-600">{{ $task->project->name }}</td><td class="px-5 py-4 text-slate-600">{{ $task->assignee?->name ?: $task->assignee?->email ?: 'Unassigned' }}</td><td class="px-5 py-4"><x-status-badge :status="$task->status" /></td><td class="px-5 py-4"><x-priority-badge :priority="$task->priority" /></td><td @class(['px-5 py-4 text-sm', 'font-semibold text-rose-700' => $task->due_at && $task->due_at->isPast() && !in_array($task->status->value, ['done', 'cancelled'], true), 'text-slate-500' => !($task->due_at && $task->due_at->isPast() && !in_array($task->status->value, ['done', 'cancelled'], true))])>{{ $task->due_at?->format('M j, Y') ?? '—' }}</td></tr>@endforeach</tbody></table></div>
            <div class="divide-y divide-slate-100 lg:hidden">@foreach($tasks as $task)<a href="{{ route('tasks.show', $task) }}" class="block p-5 transition hover:bg-slate-50"><div class="flex items-start justify-between gap-3"><div class="min-w-0"><p class="text-xs font-semibold text-indigo-700">{{ $task->number }}</p><p class="mt-1 truncate font-semibold text-slate-950">{{ $task->title }}</p><p class="mt-1 text-sm text-slate-500">{{ $task->project->name }} · {{ $task->assignee?->name ?: 'Unassigned' }}</p></div><div class="flex shrink-0 flex-col items-end gap-2"><x-status-badge :status="$task->status" /><x-priority-badge :priority="$task->priority" /></div></div><p @class(['mt-3 text-xs', 'font-semibold text-rose-700' => $task->due_at && $task->due_at->isPast() && !in_array($task->status->value, ['done', 'cancelled'], true), 'text-slate-500' => !($task->due_at && $task->due_at->isPast() && !in_array($task->status->value, ['done', 'cancelled'], true))])>Due {{ $task->due_at?->format('M j, Y') ?? 'not set' }}</p></a>@endforeach</div>
            <div class="border-t border-slate-100 px-5 py-4">{{ $tasks->links() }}</div>
        </section>
    @endif
@endsection
